// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAA9HHWbgU4Kr8W8EzGxU8t-RHFkmnQiOo',
    appId: '1:688666955776:web:89d700607e75baaa0e48e5',
    messagingSenderId: '688666955776',
    projectId: 'basics2flutter',
    authDomain: 'basics2flutter.firebaseapp.com',
    storageBucket: 'basics2flutter.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCaUp3CwNHJGir3YIFinc3HyktuOrDrt8A',
    appId: '1:688666955776:android:dcb15cbc20739d5c0e48e5',
    messagingSenderId: '688666955776',
    projectId: 'basics2flutter',
    storageBucket: 'basics2flutter.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC6WMYM7eVYkNVuqKSKEJnAEtHNz2uM9a4',
    appId: '1:688666955776:ios:ce15fa046bd272ac0e48e5',
    messagingSenderId: '688666955776',
    projectId: 'basics2flutter',
    storageBucket: 'basics2flutter.firebasestorage.app',
    iosBundleId: 'com.example.basicsToFlutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC6WMYM7eVYkNVuqKSKEJnAEtHNz2uM9a4',
    appId: '1:688666955776:ios:ce15fa046bd272ac0e48e5',
    messagingSenderId: '688666955776',
    projectId: 'basics2flutter',
    storageBucket: 'basics2flutter.firebasestorage.app',
    iosBundleId: 'com.example.basicsToFlutter',
  );

}